jenkins:
  securityRealm:
    local:
      allowsSignup: false
      users:
        # puede hacer cualquier cosa con nuestra instancia
        - id: ${JENKINS_NOMBRE_ADMINISTRADOR:-administrador}
          name: ${JENKINS_NOMBRE_ADMINISTRADOR:-administrador}
          password: ${JENKINS_PASSWORD_ADMINISTRADOR:-AdministradorTFG2024}
        # un usuario que solo puede ver los objetos de Jenkins
        - id: 'otro'
          name: 'otro usuario'
          password: ${JENKINS_PASSWORD_OTRO:-OtroTFG2024}
  authorizationStrategy:
    globalMatrix:
      permissions:
        - "Overall/Administer:${JENKINS_NOMBRE_ADMINISTRADOR:-administrador}"
        - 'Overall/Read:authenticated'

unclassified:
  location:
    url: http://servidor-jenkins:8080

jobs:
  - script: >
      pipelineJob('pipeline-correcta') {
        definition {
          cps {
            script('''
              pipeline {
                  agent any

                  stages {
                      stage('Primera fase') {
                          steps {
                              echo 'Una pipeline de prueba'
                          }
                      }
                  }
              }
            '''.stripIndent())
            sandbox()
          }
        }
      }
  - script: >
      pipelineJob('pipeline-incorrecta') {
        definition {
          cps {
            script('''
              pipeline {
                  agent any

                  stages {
                      stage('Primera fase') {
                          steps {
                              echo 'Una pipeline que debería fallar'
                              sh 'return 4'
                          }
                      }
                  }
              }
            '''.stripIndent())
            sandbox()
          }
        }
      }